## Dynamic routing configuration
http:
  routers:
    backend:
      rule: "Host(`api.microfon.com.tr`)"
      service: backend
      entryPoints:
        - web
    frontend:
      rule: "Host(`www.microfon.com.tr`) || Host(`microfon.com.tr`)"
      service: frontend
      entryPoints:
        - web

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:5173"

  middlewares:
    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        accessControlAllowOriginList:
          - "http://www.microfon.com.tr"
          - "http://microfon.com.tr"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
        accessControlMaxAge: 100
        addVaryHeader: true
