"""add autonomous enabled to users

Revision ID: 85190247a16c
Revises: 7cad38199cf7
Create Date: 2026-05-15 13:02:31.598080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85190247a16c'
down_revision = '7cad38199cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_autonomous_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_autonomous_enabled')
    # ### end Alembic commands ###
