"""add notification preferences to users

Revision ID: e6e5f7724473
Revises: 85190247a16c
Create Date: 2026-05-15 13:08:03.926255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e5f7724473'
down_revision = '85190247a16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notify_investment', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_weekly', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_market', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_market')
    op.drop_column('users', 'notify_weekly')
    op.drop_column('users', 'notify_investment')
    # ### end Alembic commands ###
